services:
  mysql:
    container_name: weather-db
    restart: on-failure
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
    ports:
      - '44444:3306'
    volumes:
      - weather:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 2
      timeout: 2s

  app:
    restart: on-failure
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  weather: {}